### ISSUE TITLE
ModuleNotFoundError: No module named 'pyeep'

### ISSUE THREAD

**Issue by alecshaw** [behinger/mne_tools#2]
The line `import pyeep` in `\libeep\__init__.py` is throwing an error because it cannot find the module.

I'm wondering if there is some missed step for the script to find `pyeep.so`. I have compiled `libeep` for macOS, and moved the `.so` and `.dylib` files into `site-packages\libeep`.

**Minimum Example**
```python
import mne
import read_antcnt

raw = read_antcnt.read_raw_antcnt(input_fname = "../Data/N5-1_P50.cnt")
```

Any guidance would be appreciated.

MNE 0.17.0
Python 3.7.2
macOS 10.14.3

**Comment by behinger** [comment]
(probably you did this) Did you put it in the same folder als the ```__init__.py```?

If this is not it I cannot give any support, you should contact Robert from ANT with additional help.

I do not maintain this library as I'm neither using MNE nor ANT anymore ;-)

**Comment by alecshaw** [comment]
I see, thanks :)
